[package]
name = "serde_db"
version = "0.5.1"
authors = ["emabee <meinolf.block@sap.com>"]
description = "Deserialization of database resultsets, and serialization of database parameters"
documentation = "https://docs.rs/serde_db/"
keywords = ["relational", "database", "driver", "serde"]
license = "MIT/Apache-2.0"
repository = "https://github.com/emabee/rust-serde_db"
readme = "README.md"

[dependencies]
log = "0.4"
serde = "1.0"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
flexi_logger = "^0.6.14"
serde_derive = "1.0"
rust_decimal = "0.7"
version-sync = "0.5"