[package]
name = "serde_db"
version = "0.1.4"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
log = "0.3"
serde = "1.0"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
flexi_logger = "0.*"
serde_derive = "*"
