[package]
name = "serde_db"
version = "0.2.0"
authors = ["emabee <meinolf.block@sap.com>"]
description = "Deserialization for database resultsets"
documentation = "https://docs.rs/serde_db/"
keywords = ["relational", "database", "driver", "serde"]
license = "Apache-2.0"

[dependencies]
log = "0.3"
serde = "1.0"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
flexi_logger = "^0.6.8"
serde_derive = "^1.0.15"
