[package]
name = "serde_db"
version = "0.1.3"
authors = ["emabee <meinolf.block@sap.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = "0.3"
serde = "1.0"
flexi_logger = "0.*"
serde_derive = "*"
